export const POMSdata = {
  statuscode: "200",
  statusmessage: "Success",
  perPage: "",
  lastPage: "",
  currentPage: "",
  total: "4",
  statuswise_count: [
    {
      purchaseorders: "1",
      supplier: "1",
      country: "1",
      product: "1",
    },
  ],
  purchaseOrders: [
    {
      orderNo: "20240715",
      orderDate: "15-Jul-2024",
      supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
      ordered: "100",
      pending: "10",
      inTransit: "60",
      delivered: "30",
      origin: "Shanghai (CN)",
      destination: "Nhava Sheva (IN)",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      action:"Track",
      products: [
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
    },
    {
      orderNo: "20241028",
      orderDate: "28-Oct-2024",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      supplierName: "UNION GARMENTS CO., LTD",
      ordered: "150",
      pending: "20",
      inTransit: "65",
      delivered: "65",
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      products: [
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
      action:"Track",
    },
    {
      orderNo: "20240923",
      orderDate: "23-09-2024",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      supplierName: "WUYI STAINLESS STEEL CO LTD",
      ordered: "150",
      pending: "20",
      inTransit: "65",
      delivered: "65",
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      products: [
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
      action:"Track",
    },
    {
      orderNo: "20242705",
      orderDate: "30-10-2024",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      supplierName: "UNION HOUSEWARES CO.,LTD",
      ordered: "150",
      pending: "20",
      inTransit: "65",
      delivered: "65",
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      products: [
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
      action:"Track",
    },
    {
      orderNo: "20241730",
      orderDate: "23-10-2024",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      supplierName: "NINGBO SPORTS PRODUCTS CO...",
      ordered: "150",
      pending: "20",
      inTransit: "65",
      delivered: "65",
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      products: [
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product:"",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
      action:"Track",
    }
  ],
  suppliers: [
    {
      supplierName: "UNION HOUSEWARES CO.,LTD",
      ordered: "100",
      pending: "50",
      booked: "10",
      inTransit: "30",
      delivered: "10",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "UNION HOUSEWARES CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "UNION HOUSEWARES CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
      action:"Track",
    },
    {
      supplierName: "WUYI STAINLESS STEEL CO LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "WUYI STAINLESS STEEL CO LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "WUYI STAINLESS STEEL CO LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
      action:"Track",
    },
    {
      supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
      action:"Track",
    },
    {
      supplierName: "ZHEJIANG POLYMER CO.,LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "ZHEJIANG POLYMER CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "ZHEJIANG POLYMER CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
      action:"Track",
    },
    {
      supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
      action:"Track",
    },
  ],
  countries: [
    {
      country: "China",
      ordered: "100",
      pending: "20",
      booked: "70",
      inTransit: "10",
      delivered: "10",
    },
    {
      country: "United Arab Emirates",
      ordered: "50",
      pending: "0",
      booked: "0",
      inTransit: "10",
      delivered: "40",
    },
  ],
};
