export const POMSdata = {
  statuscode: "200",
  statusmessage: "Success",
  perPage: "",
  lastPage: "",
  currentPage: "",
  total: "4",
  statuswise_count: [
    {
      purchaseorders: "1",
      supplier: "1",
      country: "1",
      product: "1",
    },
  ],
  purchaseOrders: [
    {
      orderNo: "20240715",
      orderDate: "15-Jul-2024",
      supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
      ordered: "100",
      pending: "10",
      inTransit: "60",
      delivered: "30",
      origin: "Shanghai",
      destination: "Nhava Sheva",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      action: "Track",
      booked_on: "03-FEB-25",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000176",
      hbl_number: "120625000666",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Arrival KUWAIT on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Estimated",
          is_updated: "",
          updated_message: "",
        },
      ],
      products: [
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
    },
    {
      orderNo: "20241028",
      orderDate: "28-Oct-2024",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      supplierName: "UNION GARMENTS CO., LTD",
      ordered: "150",
      pending: "20",
      inTransit: "65",
      delivered: "65",
      origin: "Ningbo",
      destination: "Nhava Sheva",
      booked_on: "03-FEB-25",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000221",
      hbl_number: "120625000668",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Arrival KUWAIT on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Estimated",
          is_updated: "",
          updated_message: "",
        },
      ],
      products: [
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
      action: "Track",
    },
    {
      orderNo: "20240923",
      orderDate: "23-09-2024",
      supplierName: "WUYI STAINLESS STEEL CO LTD",
      ordered: "150",
      pending: "20",
      inTransit: "65",
      delivered: "65",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      booked_on: "03-FEB-25",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000087",
      hbl_number: "120625000668",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Arrival KUWAIT on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Estimated",
          is_updated: "",
          updated_message: "",
        },
      ],
      products: [
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
      action: "Track",
    },
    {
      orderNo: "20242705",
      orderDate: "30-10-2024",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      supplierName: "UNION HOUSEWARES CO.,LTD",
      ordered: "150",
      pending: "20",
      inTransit: "65",
      delivered: "65",
      origin: "Ningbo",
      destination: "Nhava Sheva",
      booked_on: "03-FEB-25",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000038",
      hbl_number: "120625000668",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Arrival KUWAIT on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Estimated",
          is_updated: "",
          updated_message: "",
        },
      ],
      products: [
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
      action: "Track",
    },
    {
      orderNo: "20241730",
      orderDate: "23-10-2024",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      supplierName: "NINGBO SPORTS PRODUCTS CO...",
      ordered: "150",
      pending: "20",
      inTransit: "65",
      delivered: "65",
      origin: "Ningbo",
      destination: "Nhava Sheva",
      booked_on: "03-FEB-25",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000179",
      hbl_number: "120625000698",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Arrival KUWAIT on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Estimated",
          is_updated: "",
          updated_message: "",
        },
      ],
      products: [
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "10",
          booked: "40",
          inTransit: "30",
          delivered: "20",
        },
        {
          product: "",
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "50",
          booked: "30",
          inTransit: "40",
          delivered: "40",
        },
      ],
      action: "Track",
    },
  ],
  suppliers: [
    {
      supplierName: "UNION HOUSEWARES CO.,LTD",
      ordered: "100",
      pending: "50",
      booked: "10",
      inTransit: "30",
      delivered: "10",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "UNION HOUSEWARES CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
          booked_on: "03-FEB-25",
          origin_countrycode: "CN",
          destination_countrycode: "IN",
          origin: "Ningbo (CN)",
          destination: "Nhava Sheva (IN)",
          "etd/atd": "11-FEB-25",
          status: "Arrived",
          updated_message: "Test",
          estimated_departure: "11 Feb, 2025",
          actual_departure: "11 Feb, 2025",
          estimated_arrival: "11 Feb, 2025",
          "eta/ata": "11-FEB-25",
          etd_atd: "11-FEB-25",
          eta_ata: "11-FEB-25",
          mode: "AIR",
          tos: "EX WORKS",
          valid_date: "15-Jun-2024",
          id: "150225000011",
          hbl_number: "120625000698",
          milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
      ],
        },
        {
          orderNo: "20240716",
          supplierName: "UNION HOUSEWARES CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
          booked_on: "03-FEB-25",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000011",
      hbl_number: "120625000698",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
      ],
        },
      ],
      action: "Track",
    },
    {
      supplierName: "WUYI STAINLESS STEEL CO LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      delivered: "10",
      booked_on: "03-FEB-25",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000221",
      hbl_number: "120625000698",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Arrival KUWAIT on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Estimated",
          is_updated: "",
          updated_message: "",
        },
      ],
      orders: [
        {
          orderNo: "20240715",
          supplierName: "WUYI STAINLESS STEEL CO LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "WUYI STAINLESS STEEL CO LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
      action: "Track",
    },
    {
      supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      delivered: "10",
      booked_on: "03-FEB-25",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000038",
      hbl_number: "120625000698",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Arrival KUWAIT on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Estimated",
          is_updated: "",
          updated_message: "",
        },
      ],
      orders: [
        {
          orderNo: "20240715",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
      action: "Track",
    },
    {
      supplierName: "ZHEJIANG POLYMER CO.,LTD",
      ordered: "100",
      origin_countrycode: "CN",
      destination_countrycode: "IN",
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      booked_on: "03-FEB-25",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000179",
      hbl_number: "120625000698",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Arrival KUWAIT on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Estimated",
          is_updated: "",
          updated_message: "",
        },
      ],
      orders: [
        {
          orderNo: "20240715",
          supplierName: "ZHEJIANG POLYMER CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "ZHEJIANG POLYMER CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
      action: "Track",
    },
    {
      supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      booked_on: "03-FEB-25",
      "etd/atd": "11-FEB-25",
      status: "Arrived",
      updated_message: "Test",
      estimated_departure: "11 Feb, 2025",
      actual_departure: "11 Feb, 2025",
      estimated_arrival: "11 Feb, 2025",
      "eta/ata": "11-FEB-25",
      etd_atd: "11-FEB-25",
      eta_ata: "11-FEB-25",
      mode: "AIR",
      tos: "EX WORKS",
      valid_date: "15-Jun-2024",
      id: "150225000179",
      hbl_number: "120625000698",
      milestones: [
        {
          milestone: "Booked",
          date: "03 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Ready",
          date: "05 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: "Cargo Received",
          date: "08 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Departure MUMBAI on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Actual",
          is_updated: "",
          updated_message: "",
        },
        {
          milestone: " Arrival KUWAIT on AIR INDIA - IX265",
          date: "11 Feb, 2025",
          status: "COMPLETED",
          milestonestatus: "REACHED",
          milestone_status: "Estimated",
          is_updated: "",
          updated_message: "",
        },
      ],
      orders: [
        {
          orderNo: "20240715",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
      action: "Track",
    },
  ],
  countries: [
    {
      country: "China",
      countrycode: "CN",
      ordered: "100",
      pending: "20",
      booked: "70",
      inTransit: "10",
      delivered: "10",
      action: "Track",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "200",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
    },
    {
      country: "United Arab Emirates",
      countrycode: "AE",
      ordered: "50",
      pending: "0",
      booked: "0",
      inTransit: "10",
      delivered: "40",
      action: "Track",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
    },
    {
      country: "INDIA",
      countrycode: "IN",
      ordered: "50",
      pending: "0",
      booked: "0",
      inTransit: "10",
      delivered: "40",
      action: "Track",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
    },
    {
      country: "Singapore",
      countrycode: "SG",
      ordered: "50",
      pending: "0",
      booked: "0",
      inTransit: "10",
      delivered: "40",
      action: "Track",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
    },
    {
      country: "Malaysia",
      countrycode: "MY",
      ordered: "50",
      pending: "0",
      booked: "0",
      inTransit: "10",
      delivered: "40",
      action: "Track",
      orders: [
        {
          orderNo: "20240715",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "150",
          pending: "0",
          booked: "0",
          inTransit: "0",
          delivered: "100",
        },
        {
          orderNo: "20240716",
          supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
          ordered: "100",
          pending: "0",
          booked: "0",
          inTransit: "100",
          delivered: "100",
        },
      ],
    },
  ],
  products: [
    {
      product: "",
      productCode: "T1S01CN",
      productName: "Cotton T-Shirt",
      supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      action: "Track",
    },
    {
      product: "",
      productCode: "T1S02CN",
      productName: "Poly T-Shirt",
      supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      action: "Track",
    },
    {
      product: "",
      productCode: "T1S03CN",
      productName: "Lycra T-Shirt",
      supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      action: "Track",
    },
    {
      product: "",
      productCode: "T1S04CN",
      productName: "Cotton-Premium T-Shirt",
      supplierName: "SHAOXING NICHE TEXTILE CO.,LTD",
      ordered: "100",
      pending: "60",
      booked: "10",
      inTransit: "20",
      delivered: "10",
      action: "Track",
    },
  ],
};
