export const POMSdata = {
  statuscode: "200",
  statusmessage: "Success",
  perPage: "",
  lastPage: "",
  currentPage: "",
  total: "4",
  statuswise_count: [
    {
      purchaseorders: "1",
      supplier: "1",
      country: "1",
      product: "1",
    },
  ],
  purchaseOrders: [
    {
      orderNo: "20240715",
      orderDate: "15-Jul-2024",
      supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
      ordered: 100,
      pending: 10,
      inTransit: 60,
      delivered: 30,
      origin: "Shanghai (CN)",
      destination: "Nhava Sheva (IN)",
      products: [
        {
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: 100,
          pending: 10,
          booked: 10,
          inTransit: 50,
          delivered: 30,
        },
        {
          productCode: "T1S01CN",
          productName: "Cotton T-Shirt",
          supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
          ordered: 100,
          pending: 10,
          booked: 10,
          inTransit: 50,
          delivered: 30,
        },
      ],
    },
    {
      orderNo: "20241028",
      orderDate: "28-Oct-2024",
      supplierName: "UNION GARMENTS CO., LTD",
      ordered: 150,
      pending: 20,
      inTransit: 65,
      delivered: 65,
      origin: "Ningbo (CN)",
      destination: "Nhava Sheva (IN)",
      products: [],
    },
  ],
  suppliers: [
    {
      supplierName: "NINGBO SPORTS PRODUCTS CO., LTD",
      ordered: 100,
      pending: 100,
      booked: 100,
      inTransit: 100,
      delivered: 100,
      orders: [
        {
          orderNo: "20240715",
          ordered: 150,
          pending: 0,
          booked: 0,
          inTransit: 0,
          delivered: 100,
        },
        {
          orderNo: "20240716",
          ordered: 100,
          pending: 0,
          booked: 0,
          inTransit: 100,
          delivered: 100,
        },
      ],
    },
  ],
  countries: [
    {
      country: "China",
      ordered: 100,
      pending: 20,
      booked: 70,
      inTransit: 10,
      delivered: 10,
    },
    {
      country: "United Arab Emirates",
      ordered: 50,
      pending: 0,
      booked: 0,
      inTransit: 10,
      delivered: 40,
    },
  ],
};
